
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hanan
 */
public class Form_TambahIzin extends javax.swing.JFrame {

    static String kosong="",kolomnama,kolomtanggal,Tanggal,Bulan,Tahun,kolomalasan;
    static String BatasTanggal,BatasBulan,BatasTahun,kolombatastanggal,akunlogin,KOLOMNIS;
        static int kolomnis,tanggal,bulan,tahun,batastanggal,batasbulan,batastahun;
        static String sql="insert into tabel_dataizinsantri values (?,?,?,?,?,?)";
    static PreparedStatement PS;
    /**
     * Creates new form Form_TambahIzin
     */
    public Form_TambahIzin(String AkunLogin) {
        initComponents();
        akunlogin=AkunLogin;
        LabelInformasi.setVisible(false);
        KolomNIS.setBackground(new Color(0,0,0,0));
            KolomNama.setBackground(new Color(0,0,0,0));
                KolomTanggalIzin.setBackground(new Color(0,0,0,0));
            KolomAlasanIzin.setBackground(new Color(0,0,0,0));
        KolomBatasTanggalIzin.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonBack = new javax.swing.JButton();
        ButtonSimpan = new javax.swing.JButton();
        LabelNIS = new javax.swing.JLabel();
        KolomNIS = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        LabelNama = new javax.swing.JLabel();
        KolomNama = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        LabelTanggalIzin = new javax.swing.JLabel();
        KolomTanggalIzin = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        LabelAlasanIzin = new javax.swing.JLabel();
        KolomAlasanIzin = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        LabelBatasTanggalIzin = new javax.swing.JLabel();
        KolomBatasTanggalIzin = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        LabelInformasi = new javax.swing.JLabel();
        BackgroundFormTambah = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        ButtonBack.setBackground(new java.awt.Color(0, 0, 0));
        ButtonBack.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ButtonBack.setForeground(new java.awt.Color(204, 204, 204));
        ButtonBack.setText("Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonBack);
        ButtonBack.setBounds(30, 470, 80, 24);

        ButtonSimpan.setBackground(new java.awt.Color(0, 0, 0));
        ButtonSimpan.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ButtonSimpan.setForeground(new java.awt.Color(204, 204, 204));
        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSimpan);
        ButtonSimpan.setBounds(290, 470, 80, 24);

        LabelNIS.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        LabelNIS.setForeground(new java.awt.Color(0, 0, 0));
        LabelNIS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNIS.setText("Nomor Induk Santri (NIS)");
        jPanel1.add(LabelNIS);
        LabelNIS.setBounds(10, 10, 210, 32);

        KolomNIS.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        KolomNIS.setForeground(new java.awt.Color(0, 0, 0));
        KolomNIS.setText("Enter your NIS");
        KolomNIS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        KolomNIS.setOpaque(false);
        KolomNIS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KolomNISFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KolomNISFocusLost(evt);
            }
        });
        KolomNIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KolomNISKeyTyped(evt);
            }
        });
        jPanel1.add(KolomNIS);
        KolomNIS.setBounds(20, 49, 360, 30);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setOpaque(true);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 80, 360, 3);

        LabelNama.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        LabelNama.setForeground(new java.awt.Color(0, 0, 0));
        LabelNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNama.setText("Nama");
        jPanel1.add(LabelNama);
        LabelNama.setBounds(20, 90, 45, 32);

        KolomNama.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        KolomNama.setForeground(new java.awt.Color(0, 0, 0));
        KolomNama.setText("Enter your name");
        KolomNama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        KolomNama.setOpaque(false);
        KolomNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KolomNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KolomNamaFocusLost(evt);
            }
        });
        KolomNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KolomNamaKeyTyped(evt);
            }
        });
        jPanel1.add(KolomNama);
        KolomNama.setBounds(20, 130, 360, 30);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setOpaque(true);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(20, 160, 360, 3);

        LabelTanggalIzin.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        LabelTanggalIzin.setForeground(new java.awt.Color(0, 0, 0));
        LabelTanggalIzin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTanggalIzin.setText("Tanggal Izin");
        jPanel1.add(LabelTanggalIzin);
        LabelTanggalIzin.setBounds(20, 170, 89, 32);

        KolomTanggalIzin.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        KolomTanggalIzin.setForeground(new java.awt.Color(0, 0, 0));
        KolomTanggalIzin.setText("Enter your permission date (e.g, 25/12/2020)");
        KolomTanggalIzin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        KolomTanggalIzin.setOpaque(false);
        KolomTanggalIzin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KolomTanggalIzinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KolomTanggalIzinFocusLost(evt);
            }
        });
        KolomTanggalIzin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KolomTanggalIzinKeyTyped(evt);
            }
        });
        jPanel1.add(KolomTanggalIzin);
        KolomTanggalIzin.setBounds(20, 210, 360, 30);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setOpaque(true);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(20, 240, 360, 3);

        LabelAlasanIzin.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        LabelAlasanIzin.setForeground(new java.awt.Color(0, 0, 0));
        LabelAlasanIzin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAlasanIzin.setText("Alasan Izin");
        jPanel1.add(LabelAlasanIzin);
        LabelAlasanIzin.setBounds(20, 250, 81, 32);

        KolomAlasanIzin.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        KolomAlasanIzin.setForeground(new java.awt.Color(0, 0, 0));
        KolomAlasanIzin.setText("Enter your permission reason");
        KolomAlasanIzin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        KolomAlasanIzin.setOpaque(false);
        KolomAlasanIzin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KolomAlasanIzinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KolomAlasanIzinFocusLost(evt);
            }
        });
        jPanel1.add(KolomAlasanIzin);
        KolomAlasanIzin.setBounds(20, 290, 360, 30);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setOpaque(true);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(20, 320, 360, 3);

        LabelBatasTanggalIzin.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        LabelBatasTanggalIzin.setForeground(new java.awt.Color(0, 0, 0));
        LabelBatasTanggalIzin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBatasTanggalIzin.setText("Batas Tanggal Izin");
        jPanel1.add(LabelBatasTanggalIzin);
        LabelBatasTanggalIzin.setBounds(20, 330, 137, 32);

        KolomBatasTanggalIzin.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        KolomBatasTanggalIzin.setForeground(new java.awt.Color(0, 0, 0));
        KolomBatasTanggalIzin.setText("Enter your limit permission date (e.g, 25/12/2020)");
        KolomBatasTanggalIzin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        KolomBatasTanggalIzin.setOpaque(false);
        KolomBatasTanggalIzin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KolomBatasTanggalIzinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KolomBatasTanggalIzinFocusLost(evt);
            }
        });
        KolomBatasTanggalIzin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KolomBatasTanggalIzinKeyTyped(evt);
            }
        });
        jPanel1.add(KolomBatasTanggalIzin);
        KolomBatasTanggalIzin.setBounds(20, 370, 360, 30);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setOpaque(true);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(20, 400, 360, 3);

        LabelInformasi.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        LabelInformasi.setForeground(new java.awt.Color(153, 0, 0));
        LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena <br>kolom batas tanggal masih belum terisi</html>");
        LabelInformasi.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(LabelInformasi);
        LabelInformasi.setBounds(20, 410, 360, 50);

        BackgroundFormTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Background_FormTambahIzin.jpg"))); // NOI18N
        jPanel1.add(BackgroundFormTambah);
        BackgroundFormTambah.setBounds(-790, -10, 1200, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        
        setVisible(false);
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void KolomNISFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KolomNISFocusGained
        
        KolomNIS.setText("");            
    }//GEN-LAST:event_KolomNISFocusGained

    private void KolomNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KolomNamaFocusGained
        
        KolomNama.setText("");            
    }//GEN-LAST:event_KolomNamaFocusGained

    private void KolomTanggalIzinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KolomTanggalIzinFocusGained
        
        KolomTanggalIzin.setText("");        
    }//GEN-LAST:event_KolomTanggalIzinFocusGained

    private void KolomAlasanIzinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KolomAlasanIzinFocusGained
        
        KolomAlasanIzin.setText("");        
    }//GEN-LAST:event_KolomAlasanIzinFocusGained

    private void KolomBatasTanggalIzinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KolomBatasTanggalIzinFocusGained
        
        KolomBatasTanggalIzin.setText("");        
    }//GEN-LAST:event_KolomBatasTanggalIzinFocusGained

    private void KolomNISKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KolomNISKeyTyped
        
        if(KolomNIS.getText().length()>7) {evt.consume();}
    }//GEN-LAST:event_KolomNISKeyTyped

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        
        if(KolomNIS.getText().equals("Enter your NIS")) {
            if(KolomNama.getText().equals("Enter your name")) {
                if(KolomTanggalIzin.getText().equals("Enter your permission date")) {
                    if(KolomAlasanIzin.getText().equals("Enter your permission reason")) {
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan.<br>Karena"
                                                   +" semua kolom belum terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom<br>NIS, nama, tanggal, alasan & batas tanggal"
                                                   +" masih<br>belum terisi</html>");
                            LabelInformasi.setVisible(true);
                        }
                        
                    } else {
                        
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom<br>NIS, nama, tanggal & batas tanggal masih"
                                                   +" belum terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom NIS, nama & tanggal masih belum terisi"
                                                   +"</html>");
                            LabelInformasi.setVisible(true);
                        }                                                
                    }
                    
                } else {
                    
                    if(KolomAlasanIzin.getText().equals("Enter your permission reason")) {
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {

                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom <br>NIS, nama, alasan & batas tanggal masih"
                                                   +" belum terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom NIS, nama & alasan masih belum terisi"
                                                   +"</html>");
                            LabelInformasi.setVisible(true);
                        }
                        
                    } else {
                        
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom <br>NIS, nama & batas tanggal masih belum "
                                                   +"terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom NIS & nama masih belum terisi</html>");
                            LabelInformasi.setVisible(true);
                        }
                    }
                }
                
            } else {
                
                if(KolomTanggalIzin.getText().equals("Enter your permission date")) {
                    if(KolomAlasanIzin.getText().equals("Enter your permission reason")) {
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom <br>NIS, tanggal, alasan & batas tanggal "
                                                   +"masih belum terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom NIS, tanggal & alasan masih belum terisi"
                                                   +"</html>");
                            LabelInformasi.setVisible(true);
                        }
                        
                    } else {
                        
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom <br>NIS, tanggal & batas tanggal masih belum"
                                                   +" terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom NIS & tanggal masih belum terisi</html>");
                            LabelInformasi.setVisible(true);
                        }
                    }
                    
                } else {
                    
                    if(KolomAlasanIzin.getText().equals("Enter your permission reason")) {
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom <br>NIS, alasan & batas tanggal masih belum"
                                                   +" terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom NIS & alasan masih belum terisi</html>");
                            LabelInformasi.setVisible(true);
                        }
                        
                    } else {
                        
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom NIS & batas tanggal masih belum terisi"
                                                   +"</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. <br>Karena"
                                                   +" kolom NIS masih belum terisi</html>");
                            LabelInformasi.setVisible(true);
                        }
                    }
                }
            }
            
        } else {
            
            if(KolomNama.getText().equals("Enter your name")) {
                if(KolomTanggalIzin.getText().equals("Enter your permission date")) {
                    if(KolomAlasanIzin.getText().equals("Enter your permission reason")) {
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom nama, <br>tanggal, alasan & batas tanggal "
                                                   +"masih belum terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom <br>nama, tanggal & alasan masih belum terisi"
                                                   +" </html>");
                            LabelInformasi.setVisible(true);
                        }
                        
                    } else {
                        
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom <br>nama, tanggal & batas tanggal masih belum"
                                                   +" terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom nama & tanggal masih belum terisi</html>");
                            LabelInformasi.setVisible(true);
                        }
                    }    
                    
                } else {
                    
                    if(KolomAlasanIzin.getText().equals("Enter your permission reason")) {
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom <br>nama, alasan & batas tanggal masih belum"
                                                   +" terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom alasan & nama masih belum terisi</html>");
                            LabelInformasi.setVisible(true);
                        }
                        
                    } else {
                        
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom nama & batas tanggal masih belum terisi "
                                                   +"</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. <br>Karena"
                                                   +" kolom nama masih belum terisi</html>");
                            LabelInformasi.setVisible(true);
                        }
                    }
                }
                
            } else {
                
                if(KolomTanggalIzin.getText().equals("Enter your permission date")) {
                    if(KolomAlasanIzin.getText().equals("Enter your permission reason")) {
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom <br>tanggal, alasan & batas tanggal masih "
                                                   +"belum terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {

                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom tanggal & alasan masih belum terisi"
                                                   +"</html>");
                            LabelInformasi.setVisible(true);
                        }
                        
                    } else {
                        
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"kolom <br>tanggal & batas tanggal masih belum "
                                                   +"terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom tanggal masih belum terisi</html>");
                            LabelInformasi.setVisible(true);
                        }
                    }
                    
                } else {
                    
                    if(KolomAlasanIzin.getText().equals("Enter your permission reason")) {
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena "
                                                   +"<br>kolom batas tanggal & alasan masih belum terisi"
                                                   +"</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. <br>Karena"
                                                   +" kolom alasan masih belum terisi</html>");
                            LabelInformasi.setVisible(true);
                        }
                        
                    } else {
                        
                        if(KolomBatasTanggalIzin.getText().equals("Enter your limit permission date")) {
                            
                            LabelInformasi.setText("<html>Maaf, data tidak bisa kami simpan. Karena <br>"
                                                   +"kolom batas tanggal masih belum terisi</html>");
                            LabelInformasi.setVisible(true);
                            
                        } else {                            
                                
                            try {
                                    
                                kolomnis=Integer.parseInt(KolomNIS.getText());
                                kolomnama=KolomNama.getText();
                                
                                if(kolomnama.contains("0")) {
                                
                                    LabelInformasi.setText("<html>Masukkan data nama dengan benar</html>");
                                    LabelInformasi.setVisible(true);
                                
                                } else if(kolomnama.contains("1")) {
                                
                                    LabelInformasi.setText("<html>Masukkan data nama dengan benar</html>");
                                    LabelInformasi.setVisible(true);                                
                            
                                } else if(kolomnama.contains("2")) {
                                
                                    LabelInformasi.setText("<html>Masukkan data nama dengan benar</html>");
                                    LabelInformasi.setVisible(true);
                                
                                } else if(kolomnama.contains("3")) {
                                
                                    LabelInformasi.setText("<html>Masukkan data nama dengan benar</html>");
                                    LabelInformasi.setVisible(true);                                
                                
                                } else if(kolomnama.contains("4")) {
                                
                                    LabelInformasi.setText("<html>Masukkan data nama dengan benar</html>");
                                    LabelInformasi.setVisible(true);
                                
                                } else if(kolomnama.contains("5")) {
                                
                                    LabelInformasi.setText("<html>Masukkan data nama dengan benar</html>");
                                    LabelInformasi.setVisible(true);
                                
                                } else if(kolomnama.contains("6")) {
                                
                                    LabelInformasi.setText("<html>Masukkan data nama dengan benar</html>");
                                    LabelInformasi.setVisible(true);
                                    
                                } else if(kolomnama.contains("7")) {
                                    
                                    LabelInformasi.setText("<html>Masukkan data nama dengan benar</html>");
                                    LabelInformasi.setVisible(true);
                                    
                                } else if(kolomnama.contains("8")) {
                                    
                                    LabelInformasi.setText("<html>Masukkan data nama dengan benar</html>");
                                    LabelInformasi.setVisible(true);
                                    
                                } else if(kolomnama.contains("9")) {
                                    
                                    LabelInformasi.setText("<html>Masukkan data nama dengan benar</html>");
                                    LabelInformasi.setVisible(true);
                                    
                                } else {
                                    
                                    kolomtanggal=KolomTanggalIzin.getText();
                                    
                                    if(kolomtanggal.contains("/")) {
                                        
                                        Tanggal=kolomtanggal.substring(0,2);
                                        Bulan=kolomtanggal.substring(3,5);
                                        Tahun=kolomtanggal.substring(6);
                                            
                                            try {
                                                
                                                tanggal=Integer.parseInt(Tanggal);
                                                bulan=Integer.parseInt(Bulan);
                                                tahun=Integer.parseInt(Tahun);
                                                
                                                if(tanggal<1||tanggal>31) {
                                                    
                                                    LabelInformasi.setText("<html>Masukkan tanggal"
                                                                           +" izin dengan benar</html>");
                                                    LabelInformasi.setVisible(true);
                                                    
                                                } else if(bulan<1||bulan>12) {
                                                    
                                                    LabelInformasi.setText("<html>Masukkan bulan"
                                                                           +" izin dengan benar</html>");
                                                    LabelInformasi.setVisible(true);
                                                    
                                                } else if(tahun<2005) {
                                                    
                                                    LabelInformasi.setText("<html>Masukkan tahun"
                                                                           +" izin dengan benar</html>");
                                                    LabelInformasi.setVisible(true);
                                                    
                                                } else {
                                                    
                                                    kolombatastanggal=KolomBatasTanggalIzin.getText();
                                                    
                                                    if(kolombatastanggal.contains("/")) {
                                                        
                                                        BatasTanggal=kolombatastanggal.substring(0,2);
                                                        BatasBulan=kolombatastanggal.substring(3,5);
                                                        BatasTahun=kolombatastanggal.substring(6);
                                                        
                                                            if(kolombatastanggal.equals(kolomtanggal)) {
                                                                
                                                                LabelInformasi.setText("<html>Masukkan data batas tanggal"
                                                                                       +" izin dengan benar</html>");
                                                                LabelInformasi.setVisible(true);
                                                    
                                                            } else {
                                                                
                                                                try {
                                                                    
                                                                    batastanggal=Integer.parseInt(BatasTanggal);
                                                                    batasbulan=Integer.parseInt(BatasBulan);
                                                                    batastahun=Integer.parseInt(BatasTahun);
                                                                    
                                                                    if(batastanggal<1||batastanggal>31) {
                                                    
                                                                        LabelInformasi.setText("<html>Masukkan batas tanggal"
                                                                                               +" izin dengan benar</html>");
                                                                        LabelInformasi.setVisible(true);
                                                    
                                                                    } else if(batasbulan<1||batasbulan>12) {
                                                    
                                                                        LabelInformasi.setText("<html>Masukkan batas bulan"
                                                                                               +" izin dengan benar</html>");
                                                                        LabelInformasi.setVisible(true);
                                                    
                                                                    } else if(batastahun<2005) {
                                                    
                                                                        LabelInformasi.setText("<html>Masukkan batas tahun  "
                                                                                               +" izin dengan benar</html>");
                                                                        LabelInformasi.setVisible(true);
                                                    
                                                                    } else {
                                                                        
                                                                        kolomnama=KolomNama.getText();
                                                                        kolomtanggal=KolomTanggalIzin.getText();
                                                                        kolombatastanggal=KolomBatasTanggalIzin.getText();
                                                                        kolomalasan=KolomAlasanIzin.getText();
                                                                        KOLOMNIS=KolomNIS.getText();
                                                                            
                                                                            Connection con=new Izin_Santri().getConnection();
                                
                                                                        try {
                    
                                                                            PS=Izin_Santri.getConnection().prepareStatement(sql);
                                                                            PS.setString(1,akunlogin);
                                                                            PS.setString(2,KOLOMNIS);   
                                                                            PS.setString(3,kolomnama);
                                                                            PS.setString(4,kolomtanggal);
                                                                            PS.setString(5,kolomalasan);
                                                                            PS.setString(6,kolombatastanggal);
                                                                            PS.executeUpdate();
                                                                            
                                                                            setVisible(false);
                    
                                                                        } catch(Exception e) {}                                                                            
                                                                    }
                                                                    
                                                                } catch(Exception e) {
                                                                    
                                                                    LabelInformasi.setText("<html>Masukkan data batas tanggal"
                                                                                           +" izin dengan benar</html>");
                                                                    LabelInformasi.setVisible(true);
                                                                }
                                                            }
                                                        
                                                    } else {
                                                        
                                                        LabelInformasi.setText("<html>Tidak ada karakter (\"/\") "
                                                                               +"di dalam kolom batas tanggal</html>");
                                                        LabelInformasi.setVisible(true);
                                                    }
                                                }
                                                
                                            } catch(Exception e) {
                                                
                                                LabelInformasi.setText("<html>Masukkan data tanggal izin"
                                                                       +" dengan benar</html>");
                                                LabelInformasi.setVisible(true);
                                            }
                                        
                                    } else {
                                        
                                        LabelInformasi.setText("<html>Tidak ada karakter (\"/\") "
                                                                +"di dalam kolom tanggal</html>");
                                        LabelInformasi.setVisible(true);
                                    }
                                }
                                                                
                            } catch(NumberFormatException e) {
                                    
                                LabelInformasi.setText("<html>Masukkan data NIS dengan benar</html>");
                                LabelInformasi.setVisible(true);                                    
                            }                            
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void KolomNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KolomNamaKeyTyped
        
        if(KolomNama.getText().length()>44) {evt.consume();}
    }//GEN-LAST:event_KolomNamaKeyTyped

    private void KolomTanggalIzinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KolomTanggalIzinKeyTyped
        
        if(KolomTanggalIzin.getText().length()>9) {evt.consume();}
    }//GEN-LAST:event_KolomTanggalIzinKeyTyped

    private void KolomBatasTanggalIzinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KolomBatasTanggalIzinKeyTyped
        
        if(KolomBatasTanggalIzin.getText().length()>9) {evt.consume();}
    }//GEN-LAST:event_KolomBatasTanggalIzinKeyTyped

    private void KolomNISFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KolomNISFocusLost
        
        if(KolomNIS.getText().equals(kosong)) {
            
            KolomNIS.setText("Enter your NIS");
        }
    }//GEN-LAST:event_KolomNISFocusLost

    private void KolomNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KolomNamaFocusLost
        
        if(KolomNama.getText().equals(kosong)) {
            
            KolomNama.setText("Enter your name");
        }
    }//GEN-LAST:event_KolomNamaFocusLost

    private void KolomTanggalIzinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KolomTanggalIzinFocusLost
        
        if(KolomTanggalIzin.getText().equals(kosong)) {
            
            KolomTanggalIzin.setText("Enter your permission date (e.g, 25/12/2020)");
        }
    }//GEN-LAST:event_KolomTanggalIzinFocusLost

    private void KolomAlasanIzinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KolomAlasanIzinFocusLost
        
        if(KolomAlasanIzin.getText().equals(kosong)) {
            
            KolomAlasanIzin.setText("Enter your permission reason");
        }
    }//GEN-LAST:event_KolomAlasanIzinFocusLost

    private void KolomBatasTanggalIzinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KolomBatasTanggalIzinFocusLost
        
        if(KolomBatasTanggalIzin.getText().equals(kosong)) {
            
            KolomBatasTanggalIzin.setText("Enter your limit permission date (e.g, 25/12/2020)");
        }
    }//GEN-LAST:event_KolomBatasTanggalIzinFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_TambahIzin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_TambahIzin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_TambahIzin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_TambahIzin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_TambahIzin("").setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundFormTambah;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JTextField KolomAlasanIzin;
    private javax.swing.JTextField KolomBatasTanggalIzin;
    private javax.swing.JTextField KolomNIS;
    private javax.swing.JTextField KolomNama;
    private javax.swing.JTextField KolomTanggalIzin;
    private javax.swing.JLabel LabelAlasanIzin;
    private javax.swing.JLabel LabelBatasTanggalIzin;
    private javax.swing.JLabel LabelInformasi;
    private javax.swing.JLabel LabelNIS;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelTanggalIzin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
