
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hanan
 */
public class DashboardSuperAdmin extends javax.swing.JFrame {

    static String AkunLogin,NIS,NAMA,TGLIZIN,ALASANIZIN,BATASTGLIZIN,AKUN;
    static String nis,nama,tglizin,alasanizin,batastglizin,namaakun;
    static Connection con;
    static PreparedStatement PS;
    /**
     * Creates new form DashboardSuperAdmin
     */
    public DashboardSuperAdmin(String NamaUser) throws SQLException {
        
        initComponents();
        Logo();
        setResizable(false);
        con=new Izin_Santri().getConnection();
            AkunLogin=NamaUser;
            LabelNamaUser.setText("  "+AkunLogin); 
            tampilkan();
        TabelDataIzinSantri.getTableHeader().setForeground(new Color(0,0,204));
        TabelDataIzinSantri.getTableHeader().setFont(new Font("Berlin Sans FB",Font.PLAIN,13));
    }

    public static void tampilkan() throws SQLException {
        
        con=new Izin_Santri().getConnection();
        Object row[]={"Nama Akun","NIS","Nama","Tanggal Izin","Alasan Izin","Batas Tanggal Izin"};
        DefaultTableModel DTM=new DefaultTableModel(null,row);
        TabelDataIzinSantri.setModel(DTM);
        
            ResultSet rs=null;
            PS=Izin_Santri.getConnection().prepareStatement("select * from tabel_dataizinsantri");
            rs=PS.executeQuery();
        
                while(rs.next()) {
                    
                    AKUN=rs.getString(1);
                    NIS=rs.getString(2);
                    NAMA=rs.getString(3);
                    TGLIZIN=rs.getString(4);
                    ALASANIZIN=rs.getString(5);
                    BATASTGLIZIN=rs.getString(6);
                    
                        String[] baris={AKUN,NIS,NAMA,TGLIZIN,ALASANIZIN,BATASTGLIZIN};
                        DTM.addRow(baris);
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDataIzinSantri = new javax.swing.JTable();
        LabelNamaUser = new javax.swing.JLabel();
        LabelRefresh = new javax.swing.JLabel();
        ButtonTambah = new javax.swing.JButton();
        ButtonHistory = new javax.swing.JButton();
        ButtonLogOut = new javax.swing.JButton();
        ButtonPulang = new javax.swing.JButton();
        Background_Dashboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        TabelDataIzinSantri.setBackground(new java.awt.Color(204, 204, 204));
        TabelDataIzinSantri.setBorder(new javax.swing.border.MatteBorder(null));
        TabelDataIzinSantri.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        TabelDataIzinSantri.setForeground(new java.awt.Color(0, 0, 0));
        TabelDataIzinSantri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelDataIzinSantri.setFocusable(false);
        TabelDataIzinSantri.setSelectionBackground(new java.awt.Color(255, 102, 102));
        TabelDataIzinSantri.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TabelDataIzinSantri.setShowVerticalLines(false);
        TabelDataIzinSantri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataIzinSantriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelDataIzinSantri);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 190, 670, 160);

        LabelNamaUser.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        LabelNamaUser.setForeground(new java.awt.Color(255, 255, 255));
        LabelNamaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        jPanel1.add(LabelNamaUser);
        LabelNamaUser.setBounds(30, 10, 610, 90);

        LabelRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        LabelRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelRefreshMouseClicked(evt);
            }
        });
        jPanel1.add(LabelRefresh);
        LabelRefresh.setBounds(676, 150, 24, 30);

        ButtonTambah.setBackground(new java.awt.Color(0, 0, 0));
        ButtonTambah.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ButtonTambah.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plus.png"))); // NOI18N
        ButtonTambah.setText("  Tambah");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonTambah);
        ButtonTambah.setBounds(30, 130, 120, 26);

        ButtonHistory.setBackground(new java.awt.Color(0, 0, 0));
        ButtonHistory.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ButtonHistory.setForeground(new java.awt.Color(255, 255, 255));
        ButtonHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/history.png"))); // NOI18N
        ButtonHistory.setText("  History");
        ButtonHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHistoryActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonHistory);
        ButtonHistory.setBounds(510, 130, 120, 26);

        ButtonLogOut.setBackground(new java.awt.Color(0, 0, 0));
        ButtonLogOut.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ButtonLogOut.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log-out.png"))); // NOI18N
        ButtonLogOut.setText("  Log out");
        ButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonLogOut);
        ButtonLogOut.setBounds(190, 130, 120, 26);

        ButtonPulang.setBackground(new java.awt.Color(0, 0, 0));
        ButtonPulang.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ButtonPulang.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPulang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/house.png"))); // NOI18N
        ButtonPulang.setText("  Pulang");
        ButtonPulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPulangActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonPulang);
        ButtonPulang.setBounds(350, 130, 120, 26);

        Background_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BackgroundDashboard.jpg"))); // NOI18N
        jPanel1.add(Background_Dashboard);
        Background_Dashboard.setBounds(0, 0, 740, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(742, 412));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LabelRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelRefreshMouseClicked
        
        try {
            tampilkan();
        } catch (SQLException ex) {
            Logger.getLogger(DashboardSuperAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LabelRefreshMouseClicked

    private void ButtonPulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPulangActionPerformed
        
        Dialog_Pulang DP=new Dialog_Pulang(AkunLogin,nis,nama,tglizin,alasanizin,batastglizin);
        DP.setVisible(true);
    }//GEN-LAST:event_ButtonPulangActionPerformed

    private void ButtonHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHistoryActionPerformed
        
        Dashboard_History DH = null;
        try {
            DH = new Dashboard_History(AkunLogin);
        } catch (SQLException ex) {
            Logger.getLogger(DashboardSuperAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        DH.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ButtonHistoryActionPerformed

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        
        Form_TambahIzin FTI=new Form_TambahIzin(AkunLogin);
        FTI.setVisible(true);
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void ButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogOutActionPerformed
        
        Form_Login FL = null;
        try {
            FL = new Form_Login();
        } catch (SQLException ex) {
            Logger.getLogger(DashboardSuperAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        FL.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ButtonLogOutActionPerformed

    private void TabelDataIzinSantriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataIzinSantriMouseClicked
        
        int i=TabelDataIzinSantri.getSelectedRow();
        TableModel TM=TabelDataIzinSantri.getModel();
            
            namaakun=TM.getValueAt(i,0).toString();
            nis=TM.getValueAt(i,1).toString();
            nama=TM.getValueAt(i,2).toString();
            tglizin=TM.getValueAt(i,3).toString();
            alasanizin=TM.getValueAt(i,4).toString();
            batastglizin=TM.getValueAt(i,5).toString();
    }//GEN-LAST:event_TabelDataIzinSantriMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardSuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardSuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardSuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardSuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DashboardSuperAdmin("").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DashboardSuperAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background_Dashboard;
    private javax.swing.JButton ButtonHistory;
    private javax.swing.JButton ButtonLogOut;
    private javax.swing.JButton ButtonPulang;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JLabel LabelNamaUser;
    private javax.swing.JLabel LabelRefresh;
    private static javax.swing.JTable TabelDataIzinSantri;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void Logo() {
        
        setIconImage (Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
    }
}
