
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hanan
 */
public class Dashboard_History extends javax.swing.JFrame {

    static Connection con;
    static PreparedStatement PS;
    static String NIS,NAMA,TGLIZIN,ALASANIZIN,BATASTGLIZIN,AKUN,TGLPULANG,nis;
    static String AkunLogin,SyntaxSQL;
    /**
     * Creates new form Dashboard_History
     */
    public Dashboard_History(String NamaUser) throws SQLException {
        initComponents();
        tampilkan();
        Logo();
        TabelHistoryDataIzinSantri.getTableHeader().setForeground(new Color(0,0,204));
        TabelHistoryDataIzinSantri.getTableHeader().setFont(new Font("Berlin Sans FB",Font.PLAIN,13));
        AkunLogin=NamaUser;
        LabelNamaUser.setText("  "+AkunLogin);
    }
    
    public static void tampilkan() throws SQLException {
        
        con=new Izin_Santri().getConnection();
        Object row[]={"Nama Akun","NIS","Nama","Tanggal Izin","Alasan Izin","Batas Tanggal Izin","Tanggal Kepulangan"};
        DefaultTableModel DTM=new DefaultTableModel(null,row);
        TabelHistoryDataIzinSantri.setModel(DTM);
        
            ResultSet rs=null;
            PS=Izin_Santri.getConnection().prepareStatement("select * from history_dataizinsantri");
            rs=PS.executeQuery();
        
                while(rs.next()) {
                    
                    AKUN=rs.getString(1);
                    NIS=rs.getString(2);
                    NAMA=rs.getString(3);
                    TGLIZIN=rs.getString(4);
                    ALASANIZIN=rs.getString(5);
                    BATASTGLIZIN=rs.getString(6);
                    TGLPULANG=rs.getString(7);
                    
                        String[] baris={AKUN,NIS,NAMA,TGLIZIN,ALASANIZIN,BATASTGLIZIN,TGLPULANG};
                        DTM.addRow(baris);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelHistoryDataIzinSantri = new javax.swing.JTable();
        LabelNamaUser = new javax.swing.JLabel();
        ButtonBack = new javax.swing.JButton();
        LabelRecycleBin = new javax.swing.JLabel();
        Background_Dashboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        TabelHistoryDataIzinSantri.setBackground(new java.awt.Color(204, 204, 204));
        TabelHistoryDataIzinSantri.setBorder(new javax.swing.border.MatteBorder(null));
        TabelHistoryDataIzinSantri.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        TabelHistoryDataIzinSantri.setForeground(new java.awt.Color(0, 0, 0));
        TabelHistoryDataIzinSantri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelHistoryDataIzinSantri.setFocusable(false);
        TabelHistoryDataIzinSantri.setSelectionBackground(new java.awt.Color(255, 102, 102));
        TabelHistoryDataIzinSantri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelHistoryDataIzinSantriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelHistoryDataIzinSantri);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 160, 860, 190);

        LabelNamaUser.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        LabelNamaUser.setForeground(new java.awt.Color(255, 255, 255));
        LabelNamaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        jPanel1.add(LabelNamaUser);
        LabelNamaUser.setBounds(30, 10, 730, 90);

        ButtonBack.setBackground(new java.awt.Color(0, 0, 0));
        ButtonBack.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/previous.png"))); // NOI18N
        ButtonBack.setText("  Kembali");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonBack);
        ButtonBack.setBounds(30, 110, 120, 26);

        LabelRecycleBin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/recycle-bin(1).png"))); // NOI18N
        LabelRecycleBin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelRecycleBin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelRecycleBinMouseClicked(evt);
            }
        });
        jPanel1.add(LabelRecycleBin);
        LabelRecycleBin.setBounds(850, 110, 40, 40);

        Background_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Background_DashboardHistory.png"))); // NOI18N
        jPanel1.add(Background_Dashboard);
        Background_Dashboard.setBounds(-10, 0, 950, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(940, 404));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        
        DashboardSuperAdmin DSA = null;
        try {
            DSA = new DashboardSuperAdmin(AkunLogin);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard_History.class.getName()).log(Level.SEVERE, null, ex);
        }
        DSA.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void LabelRecycleBinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelRecycleBinMouseClicked
        
        con=new Izin_Santri().getConnection();
        SyntaxSQL="delete from history_dataizinsantri where nis='"+nis+"'";
        try {
            PS=Izin_Santri.getConnection().prepareStatement(SyntaxSQL);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard_History.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            PS.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard_History.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LabelRecycleBinMouseClicked

    private void TabelHistoryDataIzinSantriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelHistoryDataIzinSantriMouseClicked
        
        int i=TabelHistoryDataIzinSantri.getSelectedRow();
        TableModel TM=TabelHistoryDataIzinSantri.getModel();
            
        nis=TM.getValueAt(i,1).toString();
    }//GEN-LAST:event_TabelHistoryDataIzinSantriMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Dashboard_History("").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Dashboard_History.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background_Dashboard;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JLabel LabelNamaUser;
    private javax.swing.JLabel LabelRecycleBin;
    private static javax.swing.JTable TabelHistoryDataIzinSantri;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void Logo() {
        
        setIconImage (Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
    }
}
