/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hanan
 */
public class DashboardAdmin extends javax.swing.JFrame {

    static String NamaAkun;
    static Connection con;
    static PreparedStatement PS;
        static String NIS,NAMA,TGLIZIN,ALASANIZIN,BATASTGLIZIN;
        static String nis,nama,tglizin,alasanizin,batastglizin;
    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin(String NamaUser) throws SQLException {
        initComponents();
        con=new Izin_Santri().getConnection();
        tampilkan();
            NamaAkun=NamaUser;
            LabelNamaUserLogin.setText("   "+NamaAkun);
            Logo();
//                TableDataIzinSantri.getTableHeader().setOpaque(false);
//                TableDataIzinSantri.getTableHeader().setBackground(new Color(51,153,255));
                TabelDataIzinSantri.getTableHeader().setForeground(new Color(0,0,204));
                TabelDataIzinSantri.getTableHeader().setFont(new Font("Berlin Sans FB",Font.PLAIN,14));
            setResizable(false);
            setLocationRelativeTo(null);
    }
    
    public static void tampilkan() throws SQLException {
        
        con=new Izin_Santri().getConnection();
        Object row[]={"NIS","Nama","Tanggal Izin","Alasan Izin","Batas Tanggal Izin"};
        DefaultTableModel DTM=new DefaultTableModel(null,row);
        TabelDataIzinSantri.setModel(DTM);
        
            ResultSet rs=null;
            PS=Izin_Santri.getConnection().prepareStatement("select * from tabel_dataizinsantri");
            rs=PS.executeQuery();
        
                while(rs.next()) {
                    
                    NIS=rs.getString(2);
                    NAMA=rs.getString(3);
                    TGLIZIN=rs.getString(4);
                    ALASANIZIN=rs.getString(5);
                    BATASTGLIZIN=rs.getString(6);                                        
                    
                        String[] baris={NIS,NAMA,TGLIZIN,ALASANIZIN,BATASTGLIZIN};
                        DTM.addRow(baris);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        LabelNamaUserLogin = new javax.swing.JLabel();
        ButtonTambahIzin = new javax.swing.JButton();
        ButtonPulang = new javax.swing.JButton();
        ButtonLogOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDataIzinSantri = new javax.swing.JTable();
        LabelRefresh = new javax.swing.JLabel();
        BackgroundDashboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setLayout(null);

        LabelNamaUserLogin.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        LabelNamaUserLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelNamaUserLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        Panel1.add(LabelNamaUserLogin);
        LabelNamaUserLogin.setBounds(30, 20, 670, 70);

        ButtonTambahIzin.setBackground(new java.awt.Color(0, 0, 0));
        ButtonTambahIzin.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ButtonTambahIzin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTambahIzin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plus.png"))); // NOI18N
        ButtonTambahIzin.setText("  Tambah");
        ButtonTambahIzin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahIzinActionPerformed(evt);
            }
        });
        Panel1.add(ButtonTambahIzin);
        ButtonTambahIzin.setBounds(30, 120, 120, 30);

        ButtonPulang.setBackground(new java.awt.Color(0, 0, 0));
        ButtonPulang.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ButtonPulang.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPulang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/house.png"))); // NOI18N
        ButtonPulang.setText("  Pulang");
        ButtonPulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPulangActionPerformed(evt);
            }
        });
        Panel1.add(ButtonPulang);
        ButtonPulang.setBounds(350, 120, 120, 30);

        ButtonLogOut.setBackground(new java.awt.Color(0, 0, 0));
        ButtonLogOut.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ButtonLogOut.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log-out.png"))); // NOI18N
        ButtonLogOut.setText("Log out");
        ButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogOutActionPerformed(evt);
            }
        });
        Panel1.add(ButtonLogOut);
        ButtonLogOut.setBounds(190, 120, 120, 30);

        TabelDataIzinSantri.setBackground(new java.awt.Color(204, 204, 204));
        TabelDataIzinSantri.setBorder(new javax.swing.border.MatteBorder(null));
        TabelDataIzinSantri.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        TabelDataIzinSantri.setForeground(new java.awt.Color(0, 0, 0));
        TabelDataIzinSantri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelDataIzinSantri.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabelDataIzinSantri.setFocusable(false);
        TabelDataIzinSantri.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TabelDataIzinSantri.setSelectionBackground(new java.awt.Color(255, 102, 102));
        TabelDataIzinSantri.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TabelDataIzinSantri.setShowVerticalLines(false);
        TabelDataIzinSantri.getTableHeader().setReorderingAllowed(false);
        TabelDataIzinSantri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataIzinSantriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelDataIzinSantri);

        Panel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 180, 620, 170);

        LabelRefresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        LabelRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelRefreshMouseClicked(evt);
            }
        });
        Panel1.add(LabelRefresh);
        LabelRefresh.setBounds(620, 140, 30, 30);

        BackgroundDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BackgroundDashboard.jpg"))); // NOI18N
        Panel1.add(BackgroundDashboard);
        BackgroundDashboard.setBounds(0, 0, 690, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPulangActionPerformed
        
        Dialog_Pulang DP=new Dialog_Pulang(NamaAkun,nis,nama,tglizin,alasanizin,batastglizin);
        DP.setVisible(true);
    }//GEN-LAST:event_ButtonPulangActionPerformed

    private void ButtonTambahIzinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahIzinActionPerformed
        
        Form_TambahIzin FTI=new Form_TambahIzin(NamaAkun);
        FTI.setVisible(true);
    }//GEN-LAST:event_ButtonTambahIzinActionPerformed

    private void ButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogOutActionPerformed

        Form_Login FL = null;
        try {
            FL = new Form_Login();
        } catch (SQLException ex) {
            Logger.getLogger(DashboardAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        FL.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ButtonLogOutActionPerformed

    private void TabelDataIzinSantriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataIzinSantriMouseClicked
        
        int i=TabelDataIzinSantri.getSelectedRow();
        TableModel TM=TabelDataIzinSantri.getModel();
            
            nis=TM.getValueAt(i,0).toString();
            nama=TM.getValueAt(i,1).toString();
            tglizin=TM.getValueAt(i,2).toString();
            alasanizin=TM.getValueAt(i,3).toString();
            batastglizin=TM.getValueAt(i,4).toString();
        
//        Dialog_Pulang DP=new Dialog_Pulang(nis,nama,tglizin,alasanizin,batastglizin);
    }//GEN-LAST:event_TabelDataIzinSantriMouseClicked

    private void LabelRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelRefreshMouseClicked
        
        try {
            tampilkan();
        } catch (SQLException ex) {
            Logger.getLogger(DashboardAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LabelRefreshMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DashboardAdmin("").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DashboardAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundDashboard;
    private javax.swing.JButton ButtonLogOut;
    private javax.swing.JButton ButtonPulang;
    private javax.swing.JButton ButtonTambahIzin;
    private javax.swing.JLabel LabelNamaUserLogin;
    private javax.swing.JLabel LabelRefresh;
    private javax.swing.JPanel Panel1;
    private static javax.swing.JTable TabelDataIzinSantri;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void Logo() {
        
        setIconImage (Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
    }
}
