
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hanan
 */
public class Form_Login extends javax.swing.JFrame {

    static PreparedStatement PS;
    static Connection con;
        static ResultSet rs;
        static String SyntaxSQL;
    static String FieldNama;
    static String FieldPassword;
        static String NamaUser;
        static String informasi1="<html>Maaf, username atau password<br>yang di-input salah</html>";
    static String informasi2="<html>Tidak dapat menghubungkan ke database,<br>"+
                             "silahkan cek kembali koneksi internet anda</html>";
    
    public Form_Login() throws SQLException {
        
        initComponents();
        con=new Izin_Santri().getConnection();
        LabelEyeKnown.setVisible(false);
        LabelInformasi.setVisible(false);
        Logo();
        KolomNama.setBackground(new Color(0,0,0,0));
        KolomPassword.setBackground(new Color(0,0,0,0));
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LabelWelcome = new javax.swing.JLabel();
        LabelUsername = new javax.swing.JLabel();
        LabelPassword = new javax.swing.JLabel();
        KolomPassword = new javax.swing.JPasswordField();
        SeparatorPassword = new javax.swing.JSeparator();
        KolomNama = new javax.swing.JTextField();
        SeparatorUsername = new javax.swing.JSeparator();
        ButtonLogin = new javax.swing.JButton();
        ButtonReset = new javax.swing.JButton();
        LabelEyeUnknown = new javax.swing.JLabel();
        LabelEyeKnown = new javax.swing.JLabel();
        LabelInformasi = new javax.swing.JLabel();
        BackgroundLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(563, 335));

        jPanel2.setLayout(null);

        LabelWelcome.setFont(new java.awt.Font("Forte", 0, 48)); // NOI18N
        LabelWelcome.setForeground(new java.awt.Color(255, 51, 51));
        LabelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelWelcome.setText("WELCOME");
        jPanel2.add(LabelWelcome);
        LabelWelcome.setBounds(0, 20, 560, 50);

        LabelUsername.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        LabelUsername.setForeground(new java.awt.Color(0, 0, 0));
        LabelUsername.setText("Username    :");
        jPanel2.add(LabelUsername);
        LabelUsername.setBounds(80, 100, 170, 40);

        LabelPassword.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        LabelPassword.setForeground(new java.awt.Color(0, 0, 0));
        LabelPassword.setText("Password     :");
        jPanel2.add(LabelPassword);
        LabelPassword.setBounds(80, 180, 170, 28);

        KolomPassword.setBackground(new java.awt.Color(0, 0, 0));
        KolomPassword.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        KolomPassword.setForeground(new java.awt.Color(0, 0, 0));
        KolomPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        KolomPassword.setOpaque(false);
        KolomPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KolomPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(KolomPassword);
        KolomPassword.setBounds(250, 180, 220, 30);

        SeparatorPassword.setBackground(new java.awt.Color(0, 0, 0));
        SeparatorPassword.setForeground(new java.awt.Color(0, 0, 0));
        SeparatorPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SeparatorPassword.setOpaque(true);
        jPanel2.add(SeparatorPassword);
        SeparatorPassword.setBounds(80, 210, 400, 3);

        KolomNama.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        KolomNama.setForeground(new java.awt.Color(0, 0, 0));
        KolomNama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        KolomNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        KolomNama.setOpaque(false);
        jPanel2.add(KolomNama);
        KolomNama.setBounds(250, 100, 220, 40);

        SeparatorUsername.setBackground(new java.awt.Color(0, 0, 0));
        SeparatorUsername.setForeground(new java.awt.Color(0, 0, 0));
        SeparatorUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SeparatorUsername.setOpaque(true);
        jPanel2.add(SeparatorUsername);
        SeparatorUsername.setBounds(80, 140, 400, 3);

        ButtonLogin.setBackground(new java.awt.Color(0, 0, 0));
        ButtonLogin.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log-in.png"))); // NOI18N
        ButtonLogin.setText("Login");
        ButtonLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonLogin);
        ButtonLogin.setBounds(240, 270, 94, 34);

        ButtonReset.setBackground(new java.awt.Color(0, 0, 0));
        ButtonReset.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        ButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        ButtonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reset.png"))); // NOI18N
        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonReset);
        ButtonReset.setBounds(380, 270, 100, 34);

        LabelEyeUnknown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/unknown.png"))); // NOI18N
        LabelEyeUnknown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelEyeUnknownMousePressed(evt);
            }
        });
        jPanel2.add(LabelEyeUnknown);
        LabelEyeUnknown.setBounds(490, 190, 24, 24);

        LabelEyeKnown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/known.png"))); // NOI18N
        LabelEyeKnown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelEyeKnownMousePressed(evt);
            }
        });
        jPanel2.add(LabelEyeKnown);
        LabelEyeKnown.setBounds(490, 190, 24, 24);

        LabelInformasi.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        LabelInformasi.setForeground(new java.awt.Color(204, 0, 51));
        LabelInformasi.setText("<html>Tidak dapat menghubungkan ke database,<br>silahkan cek kembali koneksi internet anda</html>");
        jPanel2.add(LabelInformasi);
        LabelInformasi.setBounds(240, 220, 260, 40);

        BackgroundLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Background Santri.jpg"))); // NOI18N
        jPanel2.add(BackgroundLogin);
        BackgroundLogin.setBounds(0, 0, 600, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KolomPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KolomPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KolomPasswordActionPerformed

    private void LabelEyeUnknownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEyeUnknownMousePressed
        
        LabelEyeKnown.setVisible(true);
        LabelEyeUnknown.setVisible(false);
        KolomPassword.setEchoChar((char)0);
    }//GEN-LAST:event_LabelEyeUnknownMousePressed

    private void LabelEyeKnownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEyeKnownMousePressed
        
        LabelEyeKnown.setVisible(false);
        LabelEyeUnknown.setVisible(true);
        KolomPassword.setEchoChar('*');
    }//GEN-LAST:event_LabelEyeKnownMousePressed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        
        KolomNama.setText("");
        KolomPassword.setText("");
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        
        FieldNama=KolomNama.getText();
        FieldPassword=KolomPassword.getText();
        
            String HakAkses="admin";
            
            try {
                
                SyntaxSQL="select * from adminlogin where username='"+FieldNama+"'and password='"+FieldPassword+"'";
                PS=Izin_Santri.getConnection().prepareStatement(SyntaxSQL);
                rs=PS.executeQuery();                    
                    
                    if(rs.next()) {
                        
                        if(FieldNama.equalsIgnoreCase(rs.getString("username"))&&FieldPassword.equalsIgnoreCase(rs.getString("Password"))) {
                            if(HakAkses.equals(rs.getString("Hak_Akses"))) {
                                
                                NamaUser=rs.getString("Nama");
                                DashboardAdmin DA=new DashboardAdmin(NamaUser);
                                DA.setVisible(true);
                                setVisible(false);
                                
                            } else {
                                
                                NamaUser=rs.getString("Nama");
                                DashboardSuperAdmin DSA=new DashboardSuperAdmin(NamaUser);
                                DSA.setVisible(true);
                                setVisible(false);
                            }
                        }
                        
                    } else {
                        
                        LabelInformasi.setText(informasi1);
                        LabelInformasi.setVisible(true);
                    }
                
            } catch(Exception e) {
                
                LabelInformasi.setText(informasi2);
                LabelInformasi.setVisible(true);
            }
    }//GEN-LAST:event_ButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Form_Login().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Form_Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLogin;
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JTextField KolomNama;
    private javax.swing.JPasswordField KolomPassword;
    private javax.swing.JLabel LabelEyeKnown;
    private javax.swing.JLabel LabelEyeUnknown;
    private javax.swing.JLabel LabelInformasi;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JLabel LabelWelcome;
    private javax.swing.JSeparator SeparatorPassword;
    private javax.swing.JSeparator SeparatorUsername;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void Logo() {
        
        setIconImage (Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
    }
}

